blank_issues_enabled: true
contact_links:
  - name: ðŸ¤” Ask a Question
    url: "https://github.com/NLR-Distribution-Suite/shift/discussions/new?category=question"
    about: Ask a question about how to use shift using github discussions
